name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set go-version
        id: go-version
        run: |
          echo "go-version=$(grep '^go' go.mod | sed 's/go \([0-9]*\.[0-9]*\).*/\1/')" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ steps.go-version.outputs.go-version }}"
          check-latest: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
