name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set go-version
        id: go-version
        run: |
          echo "go-version=$(grep '^go' go.mod | sed 's/go \([0-9]*\.[0-9]*\).*/\1/')" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ steps.go-version.outputs.go-version }}"
          check-latest: true
      - uses: golangci/golangci-lint-action@v4
        with:
          skip-cache: true
          args: --verbose --timeout=5m
      - run: go test ./...
